import numpy as np
from pathlib import Path
import acsl_pychrono.uav as UAV_module
from acsl_pychrono.uav.uav_base import UAV_BASE

# Quad Copter Motors enumeration and Global reference frame (Reference frame acquired by SolidWorks)
#
# 2                  3
# -                  -
#   \    forward   / 
#    \      ^ X   /
#     \     |    /
#      \____|___/
#      |    |   |
#      |    |   |
#      |    |   |
#      |   O|___|______> Z right
#      |   Y up |
#      |        |
#      |________|
#      /        \
#     /          \
#    /            \
# 1 /              \ 4
# -                  -
#

class UAV (UAV_BASE) :
  def __init__(self, controller_name: str):
    super().__init__(controller_name)
    
    # Get the UAV name from the class name
    self.name = Path(__file__).stem
    
    # UAV specific parameters
    cfg = UAV_module.get_uav_config(self.name) # Config Dictionary
    
    self.loadFromYAML(cfg)  # Load generic parameters
    
    # --- UAV-specific ---
    self._load_inertia()
    self._compute_estimated_parameters()
    self._compute_mixer_matrix(cfg)
    
  def _load_inertia(self):
    # Inertia matrix of the system: (drone frame + box + propellers) espressed in Pixhawk coordinate sys (x-front, y-right, z-down), computed at the center of mass
    # Rotation Matrix that represents a fixed rotation of PI/2 rad about the X-Axis
    RotMat_YUP_2_NED = np.array([[1,  0,  0],
                                 [0,  0,  1],
                                 [0, -1,  0]])
    # Rotation Matrix that represents a fixed rotation of -PI/2 rad around the X-Axis
    RotMat_YUP_2_NED_tran = np.transpose(RotMat_YUP_2_NED)
    # Since the I_matrix_estimated was obtained in the Solidworks coordinate sys (yup), it needs to be transformed to (ned)
    self.I_matrix_estimated = np.matrix(RotMat_YUP_2_NED @ self.I_matrix_estimated @ RotMat_YUP_2_NED_tran)

  def _compute_estimated_parameters(self) -> None:
    # If sensitivity analyses are needed, the estimated parameters can be changed in this function
    # --- Basic UAV-level estimates ---
    self.surface_area_estimated = self.surface_area
    self.drag_coefficient_estimated = self.drag_coefficient
    self.air_density_estimated = self.air_density

    self.drag_coefficient_matrix_estimated = np.matrix(
      np.diag([self.drag_coefficient_estimated,
               self.drag_coefficient_estimated,
               self.drag_coefficient_estimated*2])
    )
    
  def _compute_mixer_matrix(self, cfg):
    # Mixer Matrix for the realization of the thrust generated by each motor (T1, T2, T3, T4) given the control inputs (u1, u2, u3, u4)
    l_x = float(cfg["uav"]["thrust_realization"]["mixer_matrix"]["l_x"])
    l_y = float(cfg["uav"]["thrust_realization"]["mixer_matrix"]["l_y"])
    c_t = float(cfg["uav"]["thrust_realization"]["mixer_matrix"]["c_t"])

    # Mixer matrix for QUADcopter
    # You can either input the mixer and compute the 
    # pseudo-inverse with the numpy package
    # U_mat = np.array([[ 1,    1,    1,    1  ], 
    #                   [ l_y,  l_y, -l_y, -l_y],
    #                   [-l_x,  l_x,  l_x, -l_x],
    #                   [-c_t,  c_t, -c_t,  c_t]])

    # self.U_mat_inv = np.linalg.pinv(U_mat)
    
    # Moore-Penrose pseudo-inverse of mixer matrix 
    # or give an analytical expression and save computing time
    self.U_mat_inv = np.array([
      [1/4,  1/(4*l_y), -1/(4*l_x), -1/(4*c_t)],
      [1/4,  1/(4*l_y),  1/(4*l_x),  1/(4*c_t)],
      [1/4, -1/(4*l_y),  1/(4*l_x), -1/(4*c_t)],
      [1/4, -1/(4*l_y), -1/(4*l_x),  1/(4*c_t)],
    ])